# Generated by Django 2.0.5 on 2018-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, choices=[('1', 'US'), ('2', 'Canada')], max_length=256, null=True)),
                ('artist', models.CharField(blank=True, choices=[('1', 'Lee Taemin'), ('2', 'Kim Taeyeon')], max_length=256, null=True)),
            ],
        ),
    ]
