# Generated by Django 2.0.5 on 2018-07-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='respondent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='survey.Respondent'),
        ),
    ]
