# Generated by Django 2.0.5 on 2018-07-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_respondent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='respondent',
        ),
        migrations.AddField(
            model_name='survey',
            name='authentic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
    ]
