# Generated by Django 2.0.5 on 2018-07-02 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180702_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('authentic', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='authentic',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='username',
        ),
        migrations.AddField(
            model_name='survey',
            name='respondent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='survey.Respondent'),
        ),
    ]
