# Generated by Django 2.0.5 on 2018-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20180702_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='authentic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='artist',
            field=models.CharField(choices=[('Lee Taemin', 'Lee Taemin'), ('Kim Taeyeon', 'Kim Taeyeon'), ('Kim Tae-hyung (V)', 'Kim Tae-hyung')], default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Respondent',
        ),
    ]
