# Generated by Django 2.0.5 on 2018-07-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20180703_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('authentic', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='authentic',
        ),
        migrations.AlterField(
            model_name='survey',
            name='respondent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='survey.Respondent'),
        ),
    ]
