# Generated by Django 2.0.5 on 2018-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20180703_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='artist',
            field=models.CharField(choices=[('Lee Taemin', 'Lee Taemin'), ('Kim Taeyeon', 'Kim Taeyeon'), ('Kim Tae-hyung', 'Kim Tae-hyung (V)')], default='', max_length=256),
        ),
    ]
